app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['prefix'=>'auth'], function(){
Route::resource('login', 'loginController');
	Route::get('logout',[
		'uses' => 'loginController@logout',
		'as'   => 'logout'
	]);
});
Route::resource('reporte','reportesController');



Route::group(['middleware'=>'auth'], function(){
	Route::get('/', function () {
	    return view('index');
	});

	Route::resource('cliente','clienteController');
	Route::post('cliente/create','clienteController@store');
	Route::resource('solicitud','solicitudController');
	Route::post('solicitud/create','solicitudController@store');
	Route::resource('empleado','empleadoController');
	Route::post('empleado/create','empleadoController@store');
	Route::resource('consulta','consultaController');
	Route::resource('entrega','entregaController');
});

resources/views/elementos/header.blade.php
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  @yield('header')
  <title>@yield('titulo') Reparación de Equipos</title>
   {!!Html::style('css/bootstrap.min.css')!!}
   {!!Html::style('css/style.css')!!}
   {!!Html::style('css/font-awesome.min.css')!!}
	</head>

resources/views/elementos/navbar.blade.php
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Reparación de Equipos</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        @if(Auth::user())
        @if(Auth::user()->level == 0)
          <li><a href="{{route('cliente.index')}}">Fichas del Cliente</a></li>
          <li><a href="{{route('solicitud.create')}}">Solicitud</a></li>
          <li><a href="{{route('empleado.index')}}">Empleados</a></li>
        @endif
          <li><a href="{{route('consulta.index')}}">Consulta</a></li>

        @endif
      </ul>
      @if(Auth::user())
      <ul class="nav navbar-nav navbar-right">
          <li class="pull-right"><a href="{{route('logout')}}">Salir</a></li>
      </ul>
      @endif
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>