app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['prefix'=>'auth'], function(){
Route::resource('login', 'loginController');
	Route::get('logout',[
		'uses' => 'loginController@logout',
		'as'   => 'logout'
	]);
});
Route::resource('reporte','reportesController');



Route::group(['middleware'=>'auth'], function(){
	Route::get('/', function () {
	    return view('index');
	});

	Route::resource('cliente','clienteController');
	Route::post('cliente/create','clienteController@store');
	Route::resource('solicitud','solicitudController');
	Route::post('solicitud/create','solicitudController@store');
	Route::resource('empleado','empleadoController');
	Route::post('empleado/create','empleadoController@store');
	Route::resource('consulta','consultaController');
	Route::resource('entrega','entregaController');
});

app/Empleado.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Empleado extends Model
{
    protected $table = 'empleado';
    protected $fillable = ['nombre','apellido','cedula','telefono','direccion','cargo'];
}

app/Http/Controllers/empleadoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class empleadoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = \App\Empleado::orderBy('created_at','desc')->paginate(10);
        return view('empleado.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('empleado.crear');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        \App\Empleado::create($request->all());
        return redirect()->route('empleado.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/empleado/crear.blade.php
@extends('plantillas.plantilla')
@section('content')

<div class="container">
		<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="well well-sm">
                <form class="form-horizontal" method="post">
                    {!!Form::open(['route'=>'empleado.store','method'=>'POST', 'class'=>'form-horizontal', 'files' => true, 'enctype'=>'multipart/form-data'])!!}
                    <fieldset>
                        <legend class="text-center header">Nuevo Empleado</legend>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-user bigicon"></i></span>
                            <div class="col-md-8">
                                {!!Form::text('nombre', null,['placeholder'=>'Nombre', 'class'=>'form-control'])!!}
                            </div>
                        </div>
                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-user bigicon"></i></span>
                            <div class="col-md-8">
                                {!!Form::text('apellido', null,['placeholder'=>'Apellido', 'class'=>'form-control'])!!}
                            </div>
                        </div>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-id-card-o bigicon"></i></span>
                            <div class="col-md-8">
                                {!!Form::number('cedula', null,['placeholder'=>'Cedula de identidad', 'class'=>'form-control'])!!}
                            </div>
                        </div>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-phone-square bigicon"></i></span>
                            <div class="col-md-8">
                                {!!Form::number('telefono', null,['placeholder'=>'Telefono', 'class'=>'form-control'])!!}
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-sitemap bigicon"></i></span>
                            <div class="col-md-8">
                               <select class="form-control" name="cargo" id="sel1">
                                <option>Tecnico</option>
                                <option>Administrador</option>
                                <option>Supervisor</option>
                              </select>
                            </div>
                        </div>


                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-map-marker bigicon"></i></span>
                            <div class="col-md-8">
                                {!!Form::textarea('direccion', null,['placeholder'=>'Dirección', 'class'=>'form-control'])!!}
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12 text-center">
                                <button type="submit" class="btn btn-primary btn-lg">Aceptar</button>
                            </div>
                        </div>
                    </fieldset>
                    {!!Form::close()!!}
                </form>
            </div>
        </div>
    </div>
</div>
	</div>
@endsection

resources/views/empleado/index.blade.php
@extends('plantillas.plantilla')
@section('content')

<div class="container">
		<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="well well-sm">
                    <legend class="text-center header">Empleados</legend>
                   <a href="{!!route('empleado.create')!!}"><button type="button" class="btn btn-primary btn-lg btn-block">Agregar Empleado</button></a> 
           
           <br>
                
             <table class="table table-bordered table-hover">
                    <thead class="tablaverde">
                        <tr>
                            <th>ID</th>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>Cedula</th>
                            <th>Telefono</th> 
                            <th>Cargo</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($data as $empleado)
                        <tr>
                                <td>{{$empleado->id}}</td>
                                <td>{{$empleado->nombre}}</td>
                                <td>{{$empleado->apellido}}</td>
                                <td>{{$empleado->cedula}}</td>
                                <td>{{$empleado->telefono}}</td>
                                <td>{{$empleado->cargo}}</td>
                        </tr>
                         @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
	</div>
	
@endsection