app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['prefix'=>'auth'], function(){
Route::resource('login', 'loginController');
	Route::get('logout',[
		'uses' => 'loginController@logout',
		'as'   => 'logout'
	]);
});
Route::resource('reporte','reportesController');



Route::group(['middleware'=>'auth'], function(){
	Route::get('/', function () {
	    return view('index');
	});

	Route::resource('cliente','clienteController');
	Route::post('cliente/create','clienteController@store');
	Route::resource('solicitud','solicitudController');
	Route::post('solicitud/create','solicitudController@store');
	Route::resource('empleado','empleadoController');
	Route::post('empleado/create','empleadoController@store');
	Route::resource('consulta','consultaController');
	Route::resource('entrega','entregaController');
});

app/Http/Controllers/consultaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Solicitud;

class consultaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data1= \App\Solicitud::orderBy('created_at')->paginate(10);
        return view('consulta.index',compact('data1'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data= \App\Solicitud::find($id);
        return view('consulta.ver',compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data=\App\Solicitud::find($id);
        $data->fill($request->all())->save();
        return redirect()->route('reporte.show',$id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/consulta/index.blade.php
@extends('plantillas.plantilla')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-4" style="float: right;margin-bottom: 2em;">
            <div class="input-group input-group-lg">
              <input type="text" class="form-control" placeholder="ID Solicitud">
              <span class="input-group-addon">buscar</span>
            </div>
            
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="well well-sm">
                <table class="table table-bordered table-hover">
                    <thead class="tablaverde">
                        <th>ID</th>
                        <th>IDCliente</th>
                        <th>Tipo de Equipo</th>
                        <th>Descripción de la falla</th>
                        <th>Fecha de Ingreso</th>
                        <th>Estado</th>
                        <th>Opción</th>
                    </thead>
                    <tbody>
                       @foreach($data1 as $datas1)
                        <tr>
                            <td>{{$datas1->id}}</td>
                            <td>{{$datas1->idcliente}}</td>
                            <td>{{$datas1->tipofalla}}</td>
                            <td>{{$datas1->descripcionfalla}}</td>
                            <td>{{$datas1->created_at}}</td>
                            <td>{{$datas1->estado}}</td>
                            <td><a href="{{route('consulta.show',$datas1->id)}}">Ver</a></td>
                        </tr>
                       @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@endsection
 

 
 

resources/views/consulta/ver.blade.php
@extends('plantillas.plantilla')
@section('content')
<?php
 $cliente=\App\Cliente::find($data->idcliente);
 $empleado=\App\Empleado::find($data->idempleado);
?>
<div class="container">
		<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="well well-sm ">
                    <fieldset>
                        <legend class="text-center header">Ver Consulta</legend>
            <div class="row">
			<div class="col-md-12">
				<h4>Datos de Solicitud</h4>
				<hr>
			</div>
		
			<div class="col-md-4" >
				<label>Nombre del cliente:</label> 
                <p>{{$cliente->nombre}} {{$cliente->apellido}}</p>
			</div>
			<div class="col-md-4" >
				<label>Cédula:</label> 
				<p>{{$cliente->cedula}}</p>
			</div>

			<div class="col-md-4" >
				<label>Nombre del empleado:</label> 
				<p>{{$empleado->nombre}}</p>
			</div>
			<div class="col-md-4" >
				<label>Tipo equipo:</label> 
				<p>{{$data->tipoequipo}}</p>
			</div>
			<div class="col-md-4" >
				<label>Tipo de Falla:</label> 
				<p>{{$data->tipofalla}}</p>
			</div>
			<div class="col-md-4" >
				<label>Fecha ingreso:</label> 
				<p>{{$data->created_at}}</p>
			</div>
			<div class="col-md-12" >
				<label>Descripcion de falla:</label> 
				<p>{{$data->descripcionfalla}}</p>
			</div>
			<hr>
		</div>
         <hr>
          <h4>Entregar Equipo</h4>
          <hr>
              <div class="row">
                  <div class="col-md-4 col-md-offset-4"> 
                      {!!Form::model($data,['route'=>['consulta.update',$data->id],'method'=>'PUT', 'class'=>'form-horizontal', 'files' => true, 'enctype'=>'multipart/form-data'])!!}
                          <div class="form-group">
                               {!!Form::number('costoadicional', null,['placeholder'=>'Agregue le costo adicional', 'class'=>'form-control'])!!}
                               {!!Form::hidden('estado', 'Terminado',['placeholder'=>'Agregue le costo adicional', 'class'=>'form-control'])!!}
                          </div>
                          <div class="form-group">
                               <button  class="btn btn-lg btn-primary pull-right " type="submit"> Entregar</button>
                          </div>
                      {!!Form::close()!!}
                  </div>
             </div>
          </div>
        </div>
    </div>
</div>
	</div>
@endsection