app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['prefix'=>'auth'], function(){
Route::resource('login', 'loginController');
	Route::get('logout',[
		'uses' => 'loginController@logout',
		'as'   => 'logout'
	]);
});
Route::resource('reporte','reportesController');



Route::group(['middleware'=>'auth'], function(){
	Route::get('/', function () {
	    return view('index');
	});

	Route::resource('cliente','clienteController');
	Route::post('cliente/create','clienteController@store');
	Route::resource('solicitud','solicitudController');
	Route::post('solicitud/create','solicitudController@store');
	Route::resource('empleado','empleadoController');
	Route::post('empleado/create','empleadoController@store');
	Route::resource('consulta','consultaController');
	Route::resource('entrega','entregaController');
});

app/Cliente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
    protected $table = 'cliente';
    protected $fillable = ['nombre','apellido','cedula','telefono','direccion'];
}

app/Http/Controllers/clienteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Cliente;

class clienteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $data = \App\Cliente::orderBy('created_at','desc')->paginate(10);
        return view('cliente.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cliente.crear');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        \App\Cliente::create($request->all());
        return redirect()->route('cliente.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/cliente/crear.blade.php
@extends('plantillas.plantilla')
@section('content')

<div class="container">
		<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="well well-sm">
                <form class="form-horizontal" method="post">
                    {!!Form::open(['route'=>'cliente.store','method'=>'POST', 'class'=>'form-horizontal', 'files' => true, 'enctype'=>'multipart/form-data'])!!}
                    <fieldset>
                        <legend class="text-center header">Nuevo Cliente</legend>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-user bigicon"></i></span>
                            <div class="col-md-8">
                                {!!Form::text('nombre', null,['placeholder'=>'Nombre del cliente', 'class'=>'form-control'])!!}
                            </div>
                        </div>
                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-user bigicon"></i></span>
                            <div class="col-md-8">
                                {!!Form::text('apellido', null,['placeholder'=>'Apellido del Cliente', 'class'=>'form-control'])!!}
                            </div>
                        </div>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-id-card-o bigicon"></i></span>
                            <div class="col-md-8">
                                {!!Form::number('cedula', null,['placeholder'=>'Cedula de identidad', 'class'=>'form-control'])!!}
                            </div>
                        </div>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-phone-square bigicon"></i></span>
                            <div class="col-md-8">
                                {!!Form::number('telefono', null,['placeholder'=>'Telefono del cliente', 'class'=>'form-control'])!!}
                            </div>
                        </div>

                        <div class="form-group">
                            <span class="col-md-1 col-md-offset-2 text-center"><i class="fa fa-map-marker bigicon"></i></span>
                            <div class="col-md-8">
                                {!!Form::textarea('direccion', null,['placeholder'=>'Dirección del cliente', 'class'=>'form-control'])!!}
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-12 text-center">
                                <button type="submit" class="btn btn-primary btn-lg">Aceptar</button>
                            </div>
                        </div>
                    </fieldset>
                {!!Form::close()!!}
            </div>
        </div>
    </div>
</div>
	</div>
@endsection

resources/views/cliente/index.blade.php
@extends('plantillas.plantilla')
@section('content')

<div class="container">
		<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="well well-sm">
                    <legend class="text-center header">Clientes</legend>
                   <a href="{!!route('cliente.create')!!}"><button type="button" class="btn btn-primary btn-lg btn-block">Nuevo Cliente</button></a> 
           
           <br>
             <table class="table table-bordered table-hover">
                    <thead class="tablaverde">
                        <tr>
                            <th>ID</th>
                            <th>Nombre</th>
                            <th>Apellido</th>
                            <th>Cedula</th>
                            <th>Telefono</th>
                        </tr>
                    </thead>
                    <tbody>
                       @foreach($data as $dato)
                        <tr>
                            <td>{{$dato->id}}</td>
                            <td>{{$dato->nombre}}</td>
                            <td>{{$dato->apellido}}</td>
                            <td>{{$dato->cedula}}</td>
                            <td>{{$dato->telefono}}</td>
                        </tr>      
                        @endforeach
                </table>
            </div>
        </div>
    </div>
</div>
	</div>
@endsection